### ISSUE TITLE
Just installed Yavide and saving files causes errors

### ISSUE THREAD

**Issue by ManuelMeraz** [JBakamovic/yavide#57] opened 2016-12-31 18:04 UTC
Hi there. I've been using vim for a few months now as my main text editor for school and I've become fairly comfortable with it. I have very little IDE experience in general, but I've decided to start off with this one first since I've decided to do most of my development in C++ while using Vim. 

I installed this on Xubuntu 14.04 following the instructions on your github page and it installed without any errors. I've tried googling the errors with no results and I'm not sure how to proceed. Any help would be much appreciated as I really want to make this a part of my developer toolkit!

I simply saved the file as test.cpp and these errors popped up.

![screenshot - 12312016 - 09 54 54 am](https://cloud.githubusercontent.com/assets/10673962/21578708/9f7d4de4-cf3f-11e6-8463-6c4563c2a1af.png)

**Comment by JBakamovic** [comment] 2016-12-31 18:34
This is a bug which needs to be fixed. It is caused by the assumption that `test.cpp` is part of the project context which, as it seems, you didn't create.

Current solution for you would be to create a new project or import one with existing source code. See `Project management` in [usage](https://github.com/JBakamovic/yavide/blob/master/docs/usage.md) for more details.

**Comment by ManuelMeraz** [comment] 2016-12-31 19:35
Great thanks!

I haven't worked with project files before so this is a bit new to me. 

Something that was confusing to me was the prompt for the project name and directory. It assumes that the project directory will be in the home directory and so if I type in '~/Documents/Projects' it creates the following directory structure /home/<username>/~/Documents/<project name>/. I'm not sure if this is intentional.

I'll play around with it and see if I can figure out how to use it.

**Comment by JBakamovic** [comment] 2017-01-01 12:20
Project name is a name you want to give to your project. Directory is a directory where you want to create your new project. Directory selection supports auto-completion. That's all.

**Comment by JBakamovic** [comment] 2017-01-02 22:20
Fixed with 6302966 commit.

**Closed by JBakamovic** 2017-01-02 22:20 UTC
